# Generated by Django 2.2.14 on 2020-09-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200727_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('potato', 'potato'), ('kakao', 'Kakao')], default='potato', max_length=50),
        ),
    ]
