# Generated by Django 2.2.14 on 2020-07-29 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created'], 'verbose_name_plural': 'Categories'},
        ),
    ]
