# Generated by Django 2.2.14 on 2020-08-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0005_auto_20200811_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='photo',
            field=models.ImageField(upload_to='ware_photos'),
        ),
    ]
