# Generated by Django 2.2.14 on 2020-09-16 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0007_auto_20200914_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ware', to=settings.AUTH_USER_MODEL),
        ),
    ]
